-- GROK WIDGET (4 steps)
INSERT INTO daily_plan_entries (plan_id, entry_type, title, description, zenflow_task_id, status) VALUES
(1, 'task', 'grok-1: Test Grok provider selection in chat widget', 'Verify provider dropdown shows Ollama/Grok options and state updates correctly', 'grok-1', 'pending'),
(1, 'task', 'grok-2: Configure GROK_API_KEY environment variable', 'Set up xAI API key for Grok integration testing', 'grok-2', 'pending'),
(1, 'task', 'grok-3: Test Grok API integration via chat widget', 'Send test messages through widget and verify Grok responses', 'grok-3', 'pending'),
(1, 'task', 'grok-4: Verify conversation persistence with Grok provider', 'Check ai_conversations table stores provider=grok correctly', 'grok-4', 'pending'),

-- ADD TO DAILYPLAN (5 steps)
(1, 'task', 'plan-1: Verify daily_plan_entries table created', 'Confirm table exists with all columns and indexes', 'plan-1', 'completed'),
(1, 'task', 'plan-2: Create DailyPlan record for AI Chat System project', 'Create plan entry for this enhancement project', 'plan-2', 'completed'),
(1, 'task', 'plan-3: Create all 71 step entries in daily_plan_entries', 'Populate database with all implementation steps', 'plan-3', 'in_progress'),
(1, 'task', 'plan-4: Test CRUD operations with test_daily_plan_entries.sh', 'Run comprehensive test script to verify all endpoints', 'plan-4', 'pending'),
(1, 'task', 'plan-5: Verify entries display in UI', 'Check that entries appear correctly in planning interface', 'plan-5', 'pending'),

-- SCHEMA (5 steps)
(1, 'task', 'schema-1: Access schema_compare UI', 'Navigate to /admin/schema_compare and verify it loads', 'schema-1', 'pending'),
(1, 'task', 'schema-2: Verify DailyPlanEntry Result detection', 'Confirm schema_compare detects DailyPlanEntry.pm', 'schema-2', 'pending'),
(1, 'task', 'schema-3: Review table differences', 'Check that daily_plan_entries shows correct schema', 'schema-3', 'pending'),
(1, 'task', 'schema-4: Sync any schema mismatches', 'Apply any needed schema updates via UI', 'schema-4', 'pending'),
(1, 'task', 'schema-5: Document schema_compare workflow', 'Note the process for future schema changes', 'schema-5', 'pending'),

-- PHASE 0: Chat Widget Context Awareness (12 steps)
(1, 'task', 'p0-1: Design user_context endpoint specification', 'Define /ai/user_context API contract and response format', 'p0-1', 'pending'),
(1, 'task', 'p0-2: Implement get_user_context in AI controller', 'Create endpoint to return page context, user role, available actions', 'p0-2', 'pending'),
(1, 'task', 'p0-3: Add agent configuration to context', 'Include agent_id, model_settings in context response', 'p0-3', 'pending'),
(1, 'task', 'p0-4: Implement page type detection', 'Detect admin vs user pages, specific page types', 'p0-4', 'pending'),
(1, 'task', 'p0-5: Add system_prompt generation logic', 'Create context-aware system prompts based on page', 'p0-5', 'pending'),
(1, 'task', 'p0-6: Update local-chat.js to fetch context on load', 'Add fetchPageContext() call during initialization', 'p0-6', 'pending'),
(1, 'task', 'p0-7: Modify sendAIRequest to include context', 'Send page_context with each AI request', 'p0-7', 'pending'),
(1, 'task', 'p0-8: Test context awareness on admin pages', 'Verify AI knows when user is on admin interface', 'p0-8', 'pending'),
(1, 'task', 'p0-9: Test context awareness on user pages', 'Verify AI provides user-appropriate responses', 'p0-9', 'pending'),
(1, 'task', 'p0-10: Add context refresh on page navigation', 'Update context when SPA navigation occurs', 'p0-10', 'pending'),
(1, 'task', 'p0-11: Implement context caching strategy', 'Cache context to avoid excessive API calls', 'p0-11', 'pending'),
(1, 'task', 'p0-12: Document context system for agents', 'Create guide for configuring agent context awareness', 'p0-12', 'pending'),

-- PHASE 1: Documentation Search Integration (15 steps)
(1, 'task', 'p1-1: Design AIDocSearch controller structure', 'Plan controller methods and endpoints', 'p1-1', 'pending'),
(1, 'task', 'p1-2: Create AIDocSearch.pm controller file', 'Implement base controller with search endpoint', 'p1-2', 'pending'),
(1, 'task', 'p1-3: Implement /ai/docs/search endpoint', 'Create search method with query parameter support', 'p1-3', 'pending'),
(1, 'task', 'p1-4: Add documentation source configuration', 'Define which doc sources to search (local, URLs, etc)', 'p1-4', 'pending'),
(1, 'task', 'p1-5: Implement file system doc search', 'Search local markdown/text documentation files', 'p1-5', 'pending'),
(1, 'task', 'p1-6: Add grep-based search capability', 'Use ripgrep for fast full-text search', 'p1-6', 'pending'),
(1, 'task', 'p1-7: Implement relevance ranking', 'Score and sort results by relevance', 'p1-7', 'pending'),
(1, 'task', 'p1-8: Add result excerpt extraction', 'Return context snippets around matched terms', 'p1-8', 'pending'),
(1, 'task', 'p1-9: Create doc search UI component', 'Build interface to display search results', 'p1-9', 'pending'),
(1, 'task', 'p1-10: Integrate doc search with chat widget', 'Add "Search Docs" button to chat interface', 'p1-10', 'pending'),
(1, 'task', 'p1-11: Implement auto-search on AI queries', 'Automatically search docs for relevant context', 'p1-11', 'pending'),
(1, 'task', 'p1-12: Add doc snippet injection to prompts', 'Include relevant doc excerpts in AI context', 'p1-12', 'pending'),
(1, 'task', 'p1-13: Test doc search with project docs', 'Verify search finds TECHNICAL_SPECIFICATION.md content', 'p1-13', 'pending'),
(1, 'task', 'p1-14: Add caching for doc search results', 'Cache searches to improve performance', 'p1-14', 'pending'),
(1, 'task', 'p1-15: Document doc search configuration', 'Create guide for adding new doc sources', 'p1-15', 'pending'),

-- PHASE 2: DailyPlan Testing and Verification (8 steps)
(1, 'task', 'p2-1: Run test_daily_plan_entries.sh', 'Execute full CRUD test suite', 'p2-1', 'pending'),
(1, 'task', 'p2-2: Verify entry creation via API', 'Test POST /ai/planning/daily_plan/entry', 'p2-2', 'pending'),
(1, 'task', 'p2-3: Verify entry retrieval via API', 'Test GET /ai/planning/daily_plan/entries', 'p2-3', 'pending'),
(1, 'task', 'p2-4: Verify entry update via API', 'Test PUT /ai/planning/daily_plan/entry/:id', 'p2-4', 'pending'),
(1, 'task', 'p2-5: Verify entry deletion via API', 'Test DELETE /ai/planning/daily_plan/entry/:id', 'p2-5', 'pending'),
(1, 'task', 'p2-6: Test AI conversation linking', 'Verify POST /ai/planning/daily_plan/entry/from_conversation', 'p2-6', 'pending'),
(1, 'task', 'p2-7: Test entry queries by conversation', 'Verify GET /ai/planning/daily_plan/entries/by_conversation/:id', 'p2-7', 'pending'),
(1, 'task', 'p2-8: Verify cascade delete behavior', 'Test that deleting plan deletes entries', 'p2-8', 'pending'),

-- PHASE 3: Git Integration with AIGit Controller (21 steps)
(1, 'task', 'p3-1: Design AIGit controller architecture', 'Plan controller structure and security model', 'p3-1', 'pending'),
(1, 'task', 'p3-2: Create AIGit.pm controller file', 'Implement base controller with role-based access', 'p3-2', 'pending'),
(1, 'task', 'p3-3: Implement /ai/git/status endpoint', 'Create safe git status endpoint (guest accessible)', 'p3-3', 'pending'),
(1, 'task', 'p3-4: Implement /ai/git/log endpoint', 'Create git log viewer (guest accessible)', 'p3-4', 'pending'),
(1, 'task', 'p3-5: Implement /ai/git/diff endpoint', 'Create git diff viewer (guest accessible)', 'p3-5', 'pending'),
(1, 'task', 'p3-6: Implement /ai/git/branch endpoint', 'Create branch listing (developer role required)', 'p3-6', 'pending'),
(1, 'task', 'p3-7: Implement /ai/git/commit endpoint', 'Create commit endpoint (editor role required)', 'p3-7', 'pending'),
(1, 'task', 'p3-8: Add commit message validation', 'Enforce commit message format and quality', 'p3-8', 'pending'),
(1, 'task', 'p3-9: Implement /ai/git/push endpoint', 'Create push endpoint (admin role required)', 'p3-9', 'pending'),
(1, 'task', 'p3-10: Add push safety checks', 'Verify push target, prevent force push', 'p3-10', 'pending'),
(1, 'task', 'p3-11: Implement repository path whitelist', 'Restrict git operations to approved repos', 'p3-11', 'pending'),
(1, 'task', 'p3-12: Add git operation logging', 'Log all git commands with user and timestamp', 'p3-12', 'pending'),
(1, 'task', 'p3-13: Create git operation audit trail', 'Store git actions in database for review', 'p3-13', 'pending'),
(1, 'task', 'p3-14: Implement git UI component', 'Build interface for git operations in admin panel', 'p3-14', 'pending'),
(1, 'task', 'p3-15: Add git status widget to chat', 'Show current git state in chat sidebar', 'p3-15', 'pending'),
(1, 'task', 'p3-16: Enable AI-suggested commits', 'Allow AI to propose commit messages based on diff', 'p3-16', 'pending'),
(1, 'task', 'p3-17: Test git status via API', 'Verify /ai/git/status returns correct info', 'p3-17', 'pending'),
(1, 'task', 'p3-18: Test role-based access control', 'Verify guests cannot commit/push', 'p3-18', 'pending'),
(1, 'task', 'p3-19: Test commit workflow', 'Verify editor can create commits successfully', 'p3-19', 'pending'),
(1, 'task', 'p3-20: Test push restrictions', 'Verify only admin can push to remote', 'p3-20', 'pending'),
(1, 'task', 'p3-21: Document git integration security model', 'Create guide explaining role requirements', 'p3-21', 'pending');
