requires 'Moose';
requires 'namespace::autoclean';
requires 'JSON::MaybeXS';
requires 'Term::Menus';

# System modules
requires 'Socket';
requires 'Sys::Hostname';
requires 'MooseX::MarkAsMethods';
requires 'Catalyst::Runtime' => '5.90130';
requires 'Catalyst::Model';
requires 'Catalyst::Restarter';
requires 'DBIx::Class';
requires 'DBIx::Class::Schema::Loader';
requires 'DBIx::Class::TimeStamp';
requires 'DBIx::Class::Migration';
requires 'DBIx::Class::EncodedColumn';
requires 'SQL::Translator';
requires 'DBD::MariaDB';
requires 'Object::Signature';
#json
requires 'JSON';
requires 'JSON::XS';
requires 'Config::JSON';

# Template Toolkit and plugins
requires 'Template';
requires 'Template::Plugin::DateTime';
requires 'Template::Plugin::JSON';
requires 'Template::Plugin::Number::Format';
requires 'Template::Plugin::URL';
requires 'Template::Plugin::DBI';
requires 'Template::Plugin::Markdown';

# Catalyst Plugins
requires 'Catalyst::Plugin::ConfigLoader';
requires 'Catalyst::Plugin::Static::Simple';
requires 'Catalyst::Plugin::StackTrace';
requires 'Catalyst::Plugin::Session';
requires 'Catalyst::Plugin::Session::Store::FastMmap';
requires 'Catalyst::Plugin::Session::Store::Delegate';
requires 'Catalyst::Plugin::Session::Store::DBIC';
requires 'Catalyst::Plugin::Session::Store::Cookie';
requires 'Catalyst::Plugin::Session::Store::File';
requires 'Catalyst::Plugin::Session::State::Cookie';
requires 'Catalyst::Plugin::Authentication';
requires 'Catalyst::Authentication::Store::DBIx::Class';
requires 'Catalyst::Plugin::Authorization::Roles';
requires 'Catalyst::Plugin::Authorization::ACL';
requires 'Catalyst::Plugin::Log::Dispatch';
requires 'Log::Dispatch::Config';
requires 'Catalyst::View::TT';
requires 'Catalyst::View::JSON';
# DateTime related
requires 'DateTime';
requires 'DateTime::Event::Recurrence';
requires 'DateTime::Format::Strptime';
requires 'DateTime::Format::ISO8601';
requires 'Net::CIDR';

# File handling
requires 'File::Find';
requires 'File::Basename';
requires 'File::Slurp';
requires 'Archive::Tar';

# Network related
requires 'Protocol::WebSocket';
requires 'AnyEvent';
requires 'AnyEvent::Handle';
requires 'Twiggy';
requires 'IO::Pty';

# Cryptography and Security
requires 'Crypt::CBC';
requires 'Crypt::OpenSSL::AES';
requires 'Crypt::Random';
requires 'MIME::Base64';
requires 'Digest::SHA';

# Email handling
requires 'Email::Simple';
requires 'Email::Simple::Creator';
requires 'Email::MIME';
requires 'Email::Sender::Simple';
requires 'Net::SMTP';
requires 'MIME::Lite';
requires 'Authen::SASL';
requires 'IO::Socket::SSL';
requires 'Email::Sender::Transport::SMTP';
requires 'Catalyst::View::Email';
requires 'Catalyst::View::Email::Template';

# Utility modules
requires 'URI::Escape';
requires 'Data::FormValidator';
requires 'LWP::UserAgent';
requires 'LWP::Protocol::https';
requires 'HTTP::Request';
requires 'HTTP::Parser::XS';
requires 'WWW::Form::UrlEncoded';
requires 'HTTP::Entity::Parser';
requires 'Try::Tiny';
requires 'Text::Markdown';
requires 'YAML::Tiny';
requires 'IPC::Run';
requires 'IPC::Run3';

# Development and testing
requires 'Term::ReadPassword';
requires 'Term::Size::Any';
requires 'Text::CSV';
requires 'Starman';
requires 'Test::More' => '0.88';
requires 'Test::Pod';
requires 'Test::Pod::Coverage';
requires 'Test::WWW::Mechanize::Catalyst';
requires 'Test::Exception';
requires 'Test::MockObject';
requires 'Plack::Test';
requires 'Catalyst::ScriptRunner';
requires 'Log::Log4perl';
requires 'local::lib';
