requires 'Moose';
requires 'namespace::autoclean';
requires 'JSON::MaybeXS';
requires 'Catalyst::Model';
requires 'DBI';
requires 'Paws'; # AWS SDK for Perl
requires 'Catalyst'; # Catalyst framework
requires 'Catalyst::Runtime'; # Catalyst framework
requires 'Catalyst::Plugin::ConfigLoader'; # Catalyst framework
requires 'Term::ReadPassword'; # Catalyst framework
requires 'Template::Plugin::JSON'; # Template Toolkit JSON plugin
requires 'DBIx::Class::Schema::Loader'; # DBIx::Class
requires 'Starman'; # DBIx::Class
requires 'Text::CSV'; # DBIx::Class
requires 'Config::JSON';
requires 'Catalyst::Plugin::Session';
requires 'Catalyst::Plugin::Authorization::Roles';
requires 'DBIx::Class::Migration';
requires 'DBIx::Class::TimeStamp';
requires  'Catalyst::Plugin::Log::Dispatch';
requires 'Catalyst::Plugin::Session::Store::DBI';
requires 'Catalyst::Plugin::Session::Store::File';
requires 'Log::Dispatch::Config';
requires 'DateTime::Format::Strptime';
requires 'DateTime::Format::ISO8601';
requires 'JSON';
requires  'Template::Plugin::DateTime';