#!/usr/bin/env bash
# Private TLS for ZeroTier-only dev.* (hosts file → workstation ZT IP).
# No public DNS, no Let's Encrypt, no gateway. Browsers need the local CA trusted once.
#
# Workstation (once, root):
#   ./script/dev_tls_install.sh
#
# Each dev laptop (after copying config/dev_tls/comserv-dev-ca.pem):
#   ./script/dev_tls_trust_firefox.sh
#
# Then in /etc/hosts:
#   172.30.131.126  dev.computersystemconsulting.ca dev.beemaster.ca
#
# Open: https://dev.computersystemconsulting.ca/admin  (mic works — secure context)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TLS_DIR="${AEW_TLS_CERT_DIR:-$ROOT/config/dev_tls}"
ZT_IP="${AEW_ZEROTIER_HOST:-172.30.131.126}"
LAN_IP="${AEW_LAN_IP:-192.168.1.199}"
APP_PORT="${AEW_APP_PORT:-3001}"
PLAN="$ROOT/config/infrastructure/gateway_plan.json"

CA_KEY="$TLS_DIR/comserv-dev-ca.key"
CA_PEM="$TLS_DIR/comserv-dev-ca.pem"
SRV_KEY="$TLS_DIR/comserv-dev.key"
SRV_PEM="$TLS_DIR/comserv-dev.pem"
OPENSSL_CNF="$TLS_DIR/openssl-san.cnf"

_as_root() {
    if [[ "$(id -u)" -ne 0 ]]; then
        if command -v pkexec >/dev/null 2>&1 && [[ -n "${DISPLAY:-}" ]]; then
            exec pkexec bash "$0" "$@"
        fi
        exec sudo bash "$0" "$@"
    fi
}

_collect_sans() {
    DNS_SANS=()
    IP_SANS=()
    if [[ -f "$PLAN" ]] && command -v jq >/dev/null 2>&1; then
        while IFS= read -r fqdn; do
            [[ -n "$fqdn" ]] && DNS_SANS+=("$fqdn")
        done < <(jq -r '.policy_rules[]? | select(.hostname == "dev") | .fqdn' "$PLAN" 2>/dev/null)
    fi
    DNS_SANS+=(
        dev.computersystemconsulting.ca
        dev.beemaster.ca
        workstation.zero
        workstation.local
        workstation.computersystemconsulting.ca
    )
    IP_SANS=("$ZT_IP" "$LAN_IP" "127.0.0.1")

    declare -A seen_dns seen_ip
    local -a uniq_dns=() uniq_ip=()
    local d ip
    for d in "${DNS_SANS[@]}"; do
        [[ -z "$d" || -n "${seen_dns[$d]:-}" ]] && continue
        seen_dns[$d]=1
        uniq_dns+=("$d")
    done
    for ip in "${IP_SANS[@]}"; do
        [[ -z "$ip" || -n "${seen_ip[$ip]:-}" ]] && continue
        seen_ip[$ip]=1
        uniq_ip+=("$ip")
    done
    DNS_SANS=("${uniq_dns[@]}")
    IP_SANS=("${uniq_ip[@]}")
}

_write_openssl_cnf() {
    _collect_sans
    local -a dns=("${DNS_SANS[@]}") ips=("${IP_SANS[@]}")
    local i=1
    local san_block=""
    for d in "${dns[@]}"; do
        san_block+="DNS.$i = $d"$'\n'
        ((i++)) || true
    done
    i=1
    for ip in "${ips[@]}"; do
        san_block+="IP.$i = $ip"$'\n'
        ((i++)) || true
    done

    mkdir -p "$TLS_DIR"
    cat >"$OPENSSL_CNF" <<EOF
[req]
default_bits       = 2048
prompt             = no
default_md         = sha256
distinguished_name = dn
req_extensions     = v3_req

[dn]
CN = Comserv Dev Workstation

[v3_req]
subjectAltName = @alt_names

[alt_names]
$san_block
EOF
}

_generate_certs() {
    mkdir -p "$TLS_DIR"
    chmod 700 "$TLS_DIR"

    if [[ ! -f "$CA_KEY" || ! -f "$CA_PEM" ]]; then
        echo "Generating Comserv dev CA ..."
        openssl genrsa -out "$CA_KEY" 4096
        chmod 600 "$CA_KEY"
        openssl req -x509 -new -nodes -key "$CA_KEY" -sha256 -days 3650 \
            -subj "/CN=Comserv Dev CA/O=Computer System Consulting/C=CA" \
            -out "$CA_PEM"
    fi

    _write_openssl_cnf
    echo "Generating server certificate (SANs in $OPENSSL_CNF) ..."
    openssl genrsa -out "$SRV_KEY" 2048
    chmod 600 "$SRV_KEY"
    openssl req -new -key "$SRV_KEY" -out "$TLS_DIR/comserv-dev.csr" -config "$OPENSSL_CNF"
    openssl x509 -req -in "$TLS_DIR/comserv-dev.csr" \
        -CA "$CA_PEM" -CAkey "$CA_KEY" -CAcreateserial \
        -out "$SRV_PEM" -days 825 -sha256 \
        -extfile "$OPENSSL_CNF" -extensions v3_req
    rm -f "$TLS_DIR/comserv-dev.csr" "$TLS_DIR/comserv-dev-ca.srl"
    chmod 644 "$CA_PEM" "$SRV_PEM"
}

_install_apache_ssl() {
    local src="$ROOT/script/apache_comserv_dev.conf"
    local dest="/etc/apache2/sites-available/comserv-dev.conf"
    [[ -f "$src" ]] || { echo "Missing $src"; exit 1; }

    a2enmod ssl proxy proxy_http headers >/dev/null
    cp "$src" "$dest"

    local ssl_snip="/etc/apache2/conf-available/comserv-dev-ssl-paths.conf"
    cat >"$ssl_snip" <<EOF
# Comserv private dev TLS — generated by script/dev_tls_install.sh
SSLCertificateFile    $SRV_PEM
SSLCertificateKeyFile $SRV_KEY
SSLCertificateChainFile $CA_PEM
EOF
    a2enconf comserv-dev-ssl-paths >/dev/null 2>&1 || true

    a2ensite comserv-dev.conf >/dev/null
    if [[ -e /etc/apache2/sites-enabled/000-default.conf ]]; then
        a2dissite 000-default.conf >/dev/null 2>&1 || true
    fi
    if [[ -e /etc/apache2/sites-enabled/default-ssl.conf ]]; then
        a2dissite default-ssl.conf >/dev/null 2>&1 || true
    fi

    apache2ctl configtest
    systemctl reload apache2
}

_print_next_steps() {
    echo ""
    echo "=== Comserv dev TLS ready ==="
    echo ""
    echo "Workstation Apache:"
    echo "  :80  → Starman :$APP_PORT (HTTP)"
    echo "  :443 → Starman :$APP_PORT (HTTPS, private CA)"
    echo ""
    echo "On each dev laptop — /etc/hosts (ZeroTier IP):"
    echo "  $ZT_IP  dev.computersystemconsulting.ca dev.beemaster.ca"
    echo ""
    echo "Trust the CA in Firefox (copy $CA_PEM first):"
    echo "  scp workstation:$CA_PEM ~/comserv-dev-ca.pem"
    echo "  ./script/dev_tls_trust_firefox.sh ~/comserv-dev-ca.pem"
    echo ""
    echo "Then open (secure context — mic/camera work):"
    echo "  https://dev.computersystemconsulting.ca/admin"
    echo "  https://dev.computersystemconsulting.ca/ai/widget"
    echo ""
    echo "Re-run this script after adding new dev.* zones to gateway_plan.json."
}

if [[ "${1:-}" == "--print" ]]; then
    _collect_sans
    printf 'DNS: %s\n' "${DNS_SANS[*]}"
    printf 'IP:  %s\n' "${IP_SANS[*]}"
    exit 0
fi

if [[ "${1:-}" == "--certs-only" ]]; then
    _generate_certs
    _print_next_steps
    exit 0
fi

_as_root "$@"
_generate_certs
_install_apache_ssl
_print_next_steps