package Comserv::Util::EnvFileManager;

use strict;
use warnings;
use Moose;
use autodie;
use Try::Tiny;
use File::Copy qw(copy);
use File::Basename;
use JSON;
use POSIX qw(strftime);

has 'env_path' => (
    is => 'rw',
    isa => 'Str',
    default => sub { $ENV{COMSERV_ENV_FILE} || '.env' }
);

has 'backup_dir' => (
    is => 'rw',
    isa => 'Str',
    default => sub { $_[0]->env_path . '.backups' }
);

sub read_env_file {
    my ($self) = @_;
    my %env_vars;
    
    return {} unless -f $self->env_path;
    
    try {
        open my $fh, '<', $self->env_path;
        while (my $line = <$fh>) {
            chomp $line;
            next if !$line || $line =~ /^#/;
            
            if ($line =~ /^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/) {
                my ($key, $value) = ($1, $2);
                $value = $self->_unquote_value($value);
                $env_vars{$key} = $value;
            }
        }
        close $fh;
    } catch {
        die "Error reading .env file: $_";
    };
    
    return \%env_vars;
}

sub write_env_file {
    my ($self, $env_vars, $opts) = @_;
    $opts ||= {};
    
    my $dry_run = $opts->{dry_run} // 0;
    
    if ($dry_run) {
        return $self->_generate_env_content($env_vars);
    }
    
    $self->_create_backup() if !$opts->{skip_backup};
    
    try {
        my $content = $self->_generate_env_content($env_vars);
        
        open my $fh, '>', $self->env_path;
        print $fh $content;
        close $fh;
        
        return { success => 1, message => '.env file updated successfully' };
    } catch {
        die "Error writing .env file: $_";
    };
}

sub _generate_env_content {
    my ($self, $env_vars) = @_;
    my @lines;
    
    push @lines, "# Generated by Comserv Environment Manager\n";
    push @lines, "# DO NOT EDIT DIRECTLY - Use the admin interface\n";
    push @lines, "# Last updated: " . strftime('%Y-%m-%d %H:%M:%S', localtime) . "\n\n";
    
    foreach my $key (sort keys %$env_vars) {
        my $value = $env_vars->{$key};
        my $quoted_value = $self->_quote_value($value);
        push @lines, "$key=$quoted_value\n";
    }
    
    return join '', @lines;
}

sub _quote_value {
    my ($self, $value) = @_;
    
    return '' if !defined $value;
    
    if ($value =~ /[\s"'\\$]/ || $value =~ /\n/) {
        $value =~ s/\\/\\\\/g;
        $value =~ s/"/\\"/g;
        $value =~ s/\$/\\\$/g;
        return qq("$value");
    }
    
    return $value;
}

sub _unquote_value {
    my ($self, $value) = @_;
    
    if ($value =~ /^"(.*)"$/) {
        my $unquoted = $1;
        $unquoted =~ s/\\"/"/g;
        $unquoted =~ s/\\\\/\\/g;
        $unquoted =~ s/\\\$/\$/g;
        return $unquoted;
    }
    
    return $value;
}

sub _create_backup {
    my ($self) = @_;
    
    return unless -f $self->env_path;
    
    mkdir $self->backup_dir unless -d $self->backup_dir;
    
    my $timestamp = strftime('%Y%m%d_%H%M%S', localtime);
    my $backup_file = $self->backup_dir . '/.env.' . $timestamp;
    
    copy($self->env_path, $backup_file) or die "Backup failed: $!";
    
    return $backup_file;
}

sub restore_from_backup {
    my ($self, $backup_file) = @_;
    
    $backup_file ||= $self->_get_latest_backup();
    
    return { success => 0, error => 'No backup file found' } unless $backup_file;
    return { success => 0, error => 'Backup file does not exist' } unless -f $backup_file;
    
    try {
        copy($backup_file, $self->env_path) or die $!;
        return { success => 1, message => ".env restored from $backup_file" };
    } catch {
        return { success => 0, error => "Restore failed: $_" };
    };
}

sub _get_latest_backup {
    my ($self) = @_;
    
    return undef unless -d $self->backup_dir;
    
    my @backups;
    opendir my $dh, $self->backup_dir;
    @backups = sort { $b cmp $a } 
               grep { /^\.env\./ } 
               readdir $dh;
    closedir $dh;
    
    return undef unless @backups;
    return $self->backup_dir . '/' . $backups[0];
}

sub list_backups {
    my ($self) = @_;
    
    return [] unless -d $self->backup_dir;
    
    my @backups;
    opendir my $dh, $self->backup_dir;
    @backups = sort { $b cmp $a } 
               grep { /^\.env\./ } 
               readdir $dh;
    closedir $dh;
    
    return [map { { file => $_, path => $self->backup_dir . '/' . $_ } } @backups];
}

sub detect_secrets {
    my ($self, $env_vars) = @_;
    
    my @secret_keywords = qw(
        password passwd pwd secret key token api apikey
        database_password db_password auth credential
        private_key signing_key encryption_key
    );
    
    my %secrets;
    foreach my $var_key (keys %$env_vars) {
        my $lower_key = lc $var_key;
        my @matches = grep { $lower_key =~ /$_/ } @secret_keywords;
        $secrets{$var_key} = @matches > 0;
    }
    
    return \%secrets;
}

1;
