-- Queen Log Data Model — Schema Reference
-- File: 009_queen_log_schema.sql
-- DB Project: 219 (QueenLogModel) under Apiary Management System (91)
-- Todos: 793, 794, 795, 796
--
-- THIS FILE IS REFERENCE ONLY — DO NOT EXECUTE.
-- Schema is defined by Result classes. Admin applies changes via /admin/schema_comparison.
-- Result class files are the canonical source of truth.
--
--   queens              → Comserv/lib/Comserv/Model/Schema/Ency/Result/Queen.pm
--   queen_events        → Comserv/lib/Comserv/Model/Schema/Ency/Result/QueenEvent.pm
--   queen_hive_assignments → Comserv/lib/Comserv/Model/Schema/Ency/Result/QueenHiveAssignment.pm
--   inspections.queen_id FK → Comserv/lib/Comserv/Model/Schema/Ency/Result/Inspection.pm

-- ============================================================================
-- TODO 793: queens table — extended fields (see Queen.pm)
-- ============================================================================
--
-- ARCHITECTURE:
--   Queen IS an inventory item (same pattern as Box, HiveFrame).
--   Cost and purchase date are in inventory_items — NOT duplicated here.
--   inventory_item_id = NULL while queen is a cell or virgin (pre-inventory).
--   Set inventory_item_id when: mating confirmed (home-reared) or at purchase.
--   SKU format: Q-{sitename}-{tag_number}
--
-- MULTI-TENANCY:
--   sitename on queens/queen_events/queen_hive_assignments scopes records per site.
--   Unique constraint is (tag_number, sitename) — not tag_number alone.
--
-- LOCATION MODEL:
--   location_type = 'hive'  → current_hive_configuration_id points to hive config.
--                              Hive type (full, nuc, mating_nuc) is defined by hive BOM.
--   location_type = 'cage'  → queen is in an introduction or transit cage.
--                              The cage is an inventory_item with its own location
--                              (transport_box, counter, mail) in the inventory system.
--                              location_notes = cage tag or inventory_item reference.
--
-- Fields added to queens (beyond original apiary_schema.sql):
--   sitename, genetic_line, color_marking, parent_queen_id (self-ref FK),
--   drone_source, laying_status ENUM, performance_rating, temperament_rating ENUM,
--   health_status ENUM, current_yard_id FK, current_pallet_id FK, current_position,
--   current_hive_configuration_id FK, location_type ENUM('hive','cage','unknown'),
--   location_notes, purpose ENUM, introduction_date, removal_date,
--   inventory_item_id FK → inventory_items,
--   updated_at, created_by, updated_by
--   UNIQUE KEY changed: tag_number → (tag_number, sitename)

-- ============================================================================
-- TODO 794: queen_events table (see QueenEvent.pm)
-- ============================================================================
--
-- New table — tracked per-site via sitename column.
-- event_type ENUM: grafted, emerged, mated, introduced, superseded, replaced,
--                  dead, sold, treated, moved, marked, clipped, inspected
-- FK: queen_id → queens(id) ON DELETE CASCADE
-- FK: hive_id  → hives(id)  ON DELETE SET NULL  (nullable)
-- FK: yard_id  → yards(id)  ON DELETE SET NULL  (nullable)

-- ============================================================================
-- TODO 795: queen_hive_assignments table (see QueenHiveAssignment.pm)
-- ============================================================================
--
-- New table — full history of which queen was in which hive and when.
-- removed_date NULL = currently assigned.
-- FK: queen_id → queens(id) ON DELETE CASCADE
-- FK: hive_id  → hives(id)  ON DELETE CASCADE
-- FK: yard_id  → yards(id)  ON DELETE SET NULL  (nullable, denormalised from hive)

-- ============================================================================
-- TODO 796: inspections.queen_id FK (see Inspection.pm)
-- ============================================================================
--
-- queen_id INT NULL added to inspections table.
-- FK: queen_id → queens(id) ON DELETE SET NULL
-- Records which queen was confirmed present during an inspection.
